### ISSUE TITLE
Cryptomatte layers exist in exr, but no options for layer selection in cryptomatte node

### ISSUE THREAD

**Issue by narobins** [Psyop/Cryptomatte#55] opened 2017-12-15 01:55 UTC
Hi there,

I'm able to use the cryptomatte node correctly with the sample images, but when I try to use the node with our exrs, there are no options for Layer Selection even though the exr has cryptomatte layers (they show up correctly in the viewer and are named the same as the layers in the sample images). Our exrs were rendered with Vray for Maya on a Deadline render farm. I've tried force updating the cryptomatte node and there are no visible errors. I'm using Nuke10.0v4 with the latest cryptomatte version. Any ideas of what might be going wrong in this scenario? Why would the layer selection options be empty?

Thanks for your time.

**Comment by dgirondi** [comment] 2017-12-15 07:25
Have you checked if the accompanying embed metadata is there?

Cheers,
Diogo





________________________________

**Comment by narobins** [comment] 2017-12-15 15:58
I haven't--how do I check that?

**Comment by jonahfriedman** [comment] 2017-12-15 16:17
@narobins 

Use a ViewMetaData node to check for it. However, I'd first check if you have Cryptomatte installed properly by testing with the sample images we supply. If those work, then your problem is your image. If they don't, then your problem is your installation, and see the instructions. 

Please check back when you solve it to close this.

**Comment by narobins** [comment] 2017-12-15 17:30
I have cryptomatte installed properly (it worked fine with the sample images) so I checked the meta data and it is missing. Do you know why Vray might not be including it? Is there a way to add it back?

**Comment by vkoylazov** [comment] 2017-12-15 17:44
The manifest should be there, but I don't know what's your specific setup. It might be better to contact our support team at support@chaosgroup.com and they will help you out.

Best regards,
Vlado

**Comment by jonahfriedman** [comment] 2017-12-15 18:33
Thanks Vlado! Closing this now, feel free to reopen if it turns out the issue is on this end somehow.

**Closed by jonahfriedman** 2017-12-15 18:33 UTC
