### ISSUE TITLE
nuke 11.1v1 does't seem to work with the picker

### ISSUE THREAD

**Issue by slothuus** [Psyop/Cryptomatte#56] opened 2017-12-19 02:01 UTC
the picker add and remove doesn't seem to work. 

it work doing the unload manifest 
and decryptomatte buttons, 

the images iam trying it on are render from vray. it was working fine in 11.0v3

**Comment by jonahfriedman** [comment] 2017-12-19 15:03
I just tested 11.1v1 on Windows here and it seems to work fine. Also, the whole test suite passes. 

Are you using the newest Cryptomatte version? To check your installation you can check cryptomatte_utilities.py (here: https://github.com/Psyop/Cryptomatte/blob/master/nuke/cryptomatte_utilities.py#L8)

**Comment by jonahfriedman** [comment] 2017-12-21 18:37
I'm going to close this as invalid, since it does work in 11.1v1 for me, and I don't know what version of Cryptomatte or OS you're using. Please feel free to reopen if you are on the latest version and have additional information or a way to reproduce your issues. 

One possibility, which seems likely to me but is a wild guess: Having the GPU viewer on used to break keying in older versions of Cryptomatte.

**Comment by henriktd** [comment] 2018-02-02 14:41
Hello, 

We are having the same issue in Nuke 11.1v1. We have the latest version of Cryptomatte (1.2.0), running on  Windows 10. We recently updated from version 1.1.2 to try to solve this issue, but Cryptomatte still does not work in Nuke 11. The problems are site-wide, and only applies to Nuke 11+. Cryptomatte 1.1.2 works perfectly in Nuke 10. The plugin is installed to a shared server directory in both cases.

When viewing a new crypto node connected to a read node with a cryptomatte EXR file the viewer remains black until the "Force Update All" button under the "Advanced" tab is pressed (The "Force Update" button in the main panel does not work, weirdly enough). The "Layer Selection" drop-down is also blank until Force Update All is pressed. Even after force-updating the picker does nothing, and the layer list remains empty. 

As with slothuus' case, the "Unload _Manifest" button _does_ work. 

I ran the test suite, which returned 28 cases failed and 3 errors. I've attached the test output. 

Any help would be greatly appreciated!


cheers, 

-Henrik



[crypto_v120_nuke1111_test_log_v1_htd.txt](https://github.com/Psyop/Cryptomatte/files/1689710/crypto_v120_nuke1111_test_log_v1_htd.txt)

**Comment by jonahfriedman** [comment] 2018-02-02 15:23
Thanks for that, that's very helpful. 

I suspect, based on what's failing and how, that the "knob changed" and other callbacks are not being set up properly. Those are registered when Nuke opens, in the "init.py" file, with the following code:

```
import cryptomatte_utilities
cryptomatte_utilities.setup_cryptomatte()
```

Is it possible your installation does not have that running at startup? You can also test running that from your script editor, and after that trying to use it or re-running the tests.

**Comment by henriktd** [comment] 2018-02-05 10:26
Hi Jonah, 

Your suspicions turned out to be correct - after running said lines in the script editor Cryptomatte functions perfectly.

Thanks a lot!! 

-Henrik

**Comment by jonahfriedman** [comment] 2018-02-05 15:41
@henriktd 

Thanks for confirming and re-running the tests. Did you find what it was about your installation that was causing the setup code not to run- is that anything Nuke 11 related? I'm wondering if we need a documentation update.

**Comment by jonahfriedman** [comment] 2018-02-07 19:19
I'm going to go ahead and re-close this, since it turned out to be an installation issue. Feel free to update it if there's any additional information.

**Closed by jonahfriedman** 2018-02-07 19:19 UTC

**Comment by henriktd** [comment] 2018-02-08 09:17
Hi, 

It turned out to be a simple case of Nuke 11's init.py being improperly set up for Cryptomatte. I guess I was confused by the lack of obvious error messages - we honestly suspected it was Nuke's fault, as the gizmos seemed to be properly set up and the fact that the "Unload Manifest" button worked as expected. Maybe add a section to the Troubleshooting guide?

Thanks again - Cryptomatte really is an indispensable tool!

-H.
