### ISSUE TITLE
Arnold Maya to Nuke - Cryptomatte layer selection not working on .exr inside Nuke

### ISSUE THREAD

**Issue by rmagrini** [Psyop/Cryptomatte#110] opened 2019-05-23 04:33 UTC
Hi everyone! 

I've rendered an Multi Layer .exr file with all three cryptomatte AOVs (with Merge AOVs on), exported to Nuke X, but when I try to use the Layer Selection tab, it shows nothing at all.

![help](https://user-images.githubusercontent.com/50938959/58225824-54ed0b00-7cfa-11e9-8c4d-65f7f6408d6e.png)

You can see on the print that the .exr has the cryptomatte aovs, but I can't access them... please help!!

My Maya version is 2018 update 5
Arnold version is MtoA 3.2.0.2
Arnold Core 5.3.0.2
Nuke version 11.3v3

**Comment by dgirondi** [comment] 2019-06-01 16:54
Plug a ViewMetaData node to your EXR and check if the "exr/cryptomatte"
keys are in there. If they are missing that is where the problem is.

Without the accompanying metadata Cryptomatte doesn't really work.

cheers,
Diogo

**Comment by TyrionGraphiste** [comment] 2019-06-08 14:36
I've the same issue.

**Comment by dgirondi** [comment] 2019-06-09 14:56
Have you checked metadata to see if it is there?

**Comment by TyrionGraphiste** [comment] 2019-06-10 09:10
Hello, I said there was no metadata.

**Comment by dgirondi** [comment] 2019-06-10 13:43
Hi Tim, I'm replying from email and apparently your post where you state
that didn't came trough, so I'm sorry.

Do you have "sidecar manifest" toggled on in Maya?

Not that would be the culprit but having more info doesn't hurt.

Does Cryptomatte in Nuke work properly with files generated elsewhere?

Are your cryptolayers embed on the same file as your other AOVs, single
multilayer EXR file or different files?


cheers,
diogo

**Comment by TyrionGraphiste** [comment] 2019-06-10 14:18
Hi,

Sidecar manifest isn't activated, Cryptomatte nodes work fine in Nuke with other correct EXR and the cryptolayers are embeded on the same file since int's a multilayer one.

**Comment by jonahfriedman** [comment] 2019-12-23 15:26
Hi @TyrionGraphiste,

It looks like your metadata was indeed missing. Sorry that I'm responding to this so long after it's posted. 

Is it possible this was saved out of Arnold render view instead of the result of a batch render? That's a common pitfall, no metadata is saved if you do that. 

I'm going to close this because of how long ago it was but please free free to reopen if you have more information or are still seeing this problem.

**Closed by jonahfriedman** 2019-12-23 15:26 UTC
