### ISSUE TITLE
not working on Nuke 11.2v3 ???

### ISSUE THREAD

**Issue by nuclear7799** [Psyop/Cryptomatte#91] opened 2018-09-08 10:01 UTC
![default](https://user-images.githubusercontent.com/43089234/45252944-35c66d00-b367-11e8-8532-c905e694a1bb.png)
![default](https://user-images.githubusercontent.com/43089234/45252946-3d861180-b367-11e8-87a0-118f6fa807e5.png)

**Comment by acjones** [comment] 2018-09-08 14:56
This just looks like an improper installation.  Can you take a closer look at the Nuke Documentation?  I think the problem is coming from how you downloaded the files from GitHub.  I'm going to close the issue, but you can reopen it if you are still having problems.

**Closed by acjones** 2018-09-08 14:56 UTC

**Comment by nuclear7799** [comment] 2018-09-09 12:57
still not work.

**Comment by nuclear7799** [comment] 2018-09-09 12:57
![default](https://user-images.githubusercontent.com/43089234/45264675-0556ff80-b449-11e8-8907-161b2106f446.png)

I am download full folder via download button

**Comment by nuclear7799** [comment] 2018-09-09 13:00
Work!!! when put all files directly in users/.nuke
