### ISSUE TITLE
Cryptomatte issue with deadline and many Cryptomatte layers

### ISSUE THREAD

**Issue by eoin-vstream** [Psyop/Cryptomatte#95] opened 2018-10-22 14:04 UTC
I've had some difficulty replicating this issue but I believe I've locked it down in a current nuke comp. When I send my nuke comps containing cryptomatte to Deadline to render, on the first frame on each task (task is usually set to 10 or 20 frames) I get a cryptomatte error and the comp ignores the masks generated by cryptomatte:

ERROR: Cryptomatte1.Expression_key.expr0: Nothing named 'VRayCryptomatte08.red' in '((VRayCryptomatte00.red == -177.727798462) ? VRayCryptomatte00.green : 0.0) + ((VRayCryptomatte00.blue == -177.727798462) ? VRayCryptomatte00.alpha : 0.0) + ((VRayCryptomatte01.red == -177.727798462) ? VRayCryptomatte01.green : 0.0) + ((VRayCryptomatte01.blue == -177.727798462) ? VRayCryptomatte01.alpha : 0.0) + ((VRayCryptomatte02.red == -177.727798462) ? VRayCryptomatte02.green : 0.0) + ((VRayCryptomatte02.blue == -177.727798462) ? VRayCryptomatte02.alpha : 0.0) +8u

Its strange as the rest of the frames in the tasks seem to render correctly, with the masks flashing off every 10 or 20 frames. The guys at Deadline have been looking into this but have been unable to figure it out and have asked if I can get someone from Cryptomatte in on the conversation to see if we can get to the bottom of it.

Thanks
Eoin

**Comment by jonahfriedman** [comment] 2018-11-03 16:53
Hi @eoin-vstream,

Sorry for the slow response. 

This is quite odd - we have had this problem in the past and have solved it with hidden channel knobs on the Cryptomatte nodes which ensure the channels are available when the script loads. Perhaps there's some reason those are not filled out? Are you using stock Cryptomatte or is it your own variant? 

One suggestion - in that nuke script, can you try pressing "force update all", this should ensure that the channels are filled out properly.

**Comment by eoin-vstream** [comment] 2018-11-13 15:56
No problem, busy enough in here so I'm in the same boat. 
We're using the stock Cryptomatte node, I haven't changed anything on it. "Force update all" does occasionally work but it still is a bit random, depending on the nuke script, some of them will render fine but the majority will show this error.
Using decryptomatte also works sometimes, but again, this has failed on some nuke scripts.
Thanks

**Comment by jonahfriedman** [comment] 2018-11-14 16:23
Thanks. In your error above, you had the issue on "cryptomatte1". Next time it happens, if you could open the script, and copy and paste just that node into here, that might help.

**Comment by eoin-vstream** [comment] 2018-11-15 11:15
set cut_paste_input [stack 0]
version 9.0 v8
push $cut_paste_input
add_layer {VRayCryptomatte00 VRayCryptomatte00.red VRayCryptomatte00.green VRayCryptomatte00.blue VRayCryptomatte00.alpha}
add_layer {VRayCryptomatte01 VRayCryptomatte01.red VRayCryptomatte01.green VRayCryptomatte01.blue VRayCryptomatte01.alpha}
add_layer {VRayCryptomatte02 VRayCryptomatte02.red VRayCryptomatte02.green VRayCryptomatte02.blue VRayCryptomatte02.alpha}
add_layer {VRayCryptomatte03 VRayCryptomatte03.red VRayCryptomatte03.green VRayCryptomatte03.blue VRayCryptomatte03.alpha}
add_layer {VRayCryptomatte04 VRayCryptomatte04.red VRayCryptomatte04.green VRayCryptomatte04.blue VRayCryptomatte04.alpha}
add_layer {VRayCryptomatte05 VRayCryptomatte05.red VRayCryptomatte05.green VRayCryptomatte05.blue VRayCryptomatte05.alpha}
add_layer {VRayCryptomatte06 VRayCryptomatte06.red VRayCryptomatte06.green VRayCryptomatte06.blue VRayCryptomatte06.alpha}
add_layer {VRayCryptomatte07 VRayCryptomatte07.red VRayCryptomatte07.green VRayCryptomatte07.blue VRayCryptomatte07.alpha}
Cryptomatte {
 name Cryptomatte1
 selected true
 xpos 10803
 ypos -1146
 matteOnly true
 matteOutput alpha
 matteList Amyloidotic_Particle_HP_02_v_054
 cryptoLayer VRayCryptomatte
 expression "((VRayCryptomatte00.red == -177.727798462) ? VRayCryptomatte00.green : 0.0) + ((VRayCryptomatte00.blue == -177.727798462) ? VRayCryptomatte00.alpha : 0.0) + ((VRayCryptomatte01.red == -177.727798462) ? VRayCryptomatte01.green : 0.0) + ((VRayCryptomatte01.blue == -177.727798462) ? VRayCryptomatte01.alpha : 0.0) + ((VRayCryptomatte02.red == -177.727798462) ? VRayCryptomatte02.green : 0.0) + ((VRayCryptomatte02.blue == -177.727798462) ? VRayCryptomatte02.alpha : 0.0) + ((VRayCryptomatte03.red == -177.727798462) ? VRayCryptomatte03.green : 0.0) + ((VRayCryptomatte03.blue == -177.727798462) ? VRayCryptomatte03.alpha : 0.0) + ((VRayCryptomatte04.red == -177.727798462) ? VRayCryptomatte04.green : 0.0) + ((VRayCryptomatte04.blue == -177.727798462) ? VRayCryptomatte04.alpha : 0.0) + ((VRayCryptomatte05.red == -177.727798462) ? VRayCryptomatte05.green : 0.0) + ((VRayCryptomatte05.blue == -177.727798462) ? VRayCryptomatte05.alpha : 0.0) + ((VRayCryptomatte06.red == -177.727798462) ? VRayCryptomatte06.green : 0.0) + ((VRayCryptomatte06.blue == -177.727798462) ? VRayCryptomatte06.alpha : 0.0) + ((VRayCryptomatte07.red == -177.727798462) ? VRayCryptomatte07.green : 0.0) + ((VRayCryptomatte07.blue == -177.727798462) ? VRayCryptomatte07.alpha : 0.0) + ((VRayCryptomatte08.red == -177.727798462) ? VRayCryptomatte08.green : 0.0) + ((VRayCryptomatte08.blue == -177.727798462) ? VRayCryptomatte08.alpha : 0.0) + ((VRayCryptomatte09.red == -177.727798462) ? VRayCryptomatte09.green : 0.0) + ((VRayCryptomatte09.blue == -177.727798462) ? VRayCryptomatte09.alpha : 0.0) + 0"
 keyedName ""
 previewExpression0 "((mantissa(abs(VRayCryptomatte00.red)) * 1 % 0.25) * VRayCryptomatte00.green + (mantissa(abs(VRayCryptomatte00.blue)) * 1 % 0.25) * VRayCryptomatte00.alpha + (mantissa(abs(VRayCryptomatte01.red)) * 1 % 0.25) * VRayCryptomatte01.green + (mantissa(abs(VRayCryptomatte01.blue)) * 1 % 0.25) * VRayCryptomatte01.alpha)"
 previewExpression1 "((mantissa(abs(VRayCryptomatte00.red)) * 16 % 0.25) * VRayCryptomatte00.green + (mantissa(abs(VRayCryptomatte00.blue)) * 16 % 0.25) * VRayCryptomatte00.alpha + (mantissa(abs(VRayCryptomatte01.red)) * 16 % 0.25) * VRayCryptomatte01.green + (mantissa(abs(VRayCryptomatte01.blue)) * 16 % 0.25) * VRayCryptomatte01.alpha)"
 previewExpression2 "((mantissa(abs(VRayCryptomatte00.red)) * 64 % 0.25) * VRayCryptomatte00.green + (mantissa(abs(VRayCryptomatte00.blue)) * 64 % 0.25) * VRayCryptomatte00.alpha + (mantissa(abs(VRayCryptomatte01.red)) * 64 % 0.25) * VRayCryptomatte01.green + (mantissa(abs(VRayCryptomatte01.blue)) * 64 % 0.25) * VRayCryptomatte01.alpha)"
 previewExpression3 ""
 previewChannel none
 in00 VRayCryptomatte00
 in01 VRayCryptomatte01
 in02 VRayCryptomatte02
 in03 VRayCryptomatte03
 in04 VRayCryptomatte04
 in05 VRayCryptomatte05
 in06 VRayCryptomatte06
 in07 VRayCryptomatte07
}

**Comment by jonahfriedman** [comment] 2018-11-17 16:36
Ah, I see what's happening. You have 10 layers of Cryptomatte (for 20 objects per pixel), but we're only storing the first 8 in our channel ports (which are there to avoid this exact issue). 

It's a bug on our side, but can work around it by rendering less Cryptomatte depth.

**Comment by eoin-vstream** [comment] 2018-11-19 09:40
Hi Jonah,

That's a handy solution, I had been putting the number of levels up at max
as we were getting some artifacts along the outlines. So should I set the
num levels to 8 or to 16?

Thanks
-------
Eoin Coakley
Pipeline Manager
<http://www.vstream.ie/>
<https://www.facebook.com/vStream/>

  <https://www.facebook.com/vStream/>  <https://twitter.com/vstream>
<https://www.linkedin.com/company/vstream>


 eoin@vstream.ie

 www.vstream.ie

**Comment by jonahfriedman** [comment] 2018-12-31 21:56
Sorry for the lack of response to the last question. Num levels to 8 will work better for now. I'm guessing the artifacts are probably not due to the depth setting, but I could be wrong (6 is almost always enough).

In the next release, it'll only use the maximum it can store safely, and I'm increasing that to 12. As a result, if you set it to 16 it'll only use 12 anyway. We should look at having that set dynamically as well.

**Comment by TimElschner** [comment] 2019-02-21 11:22
> Sorry for the lack of response to the last question. Num levels to 8 will work better for now. I'm guessing the artifacts are probably not due to the depth setting, but I could be wrong (6 is almost always enough).
> 
> In the next release, it'll only use the maximum it can store safely, and I'm increasing that to 12. As a result, if you set it to 16 it'll only use 12 anyway. We should look at having that set dynamically as well.

We have the same issue here, you do  mention a next release! Are there any plans to fix this, or can I even pay you to get this fixed? We are working on a small title and the crash on deadline really is a pain

**Comment by jonahfriedman** [comment] 2019-02-24 17:41
This is fixed in version 1.2.4. Thanks for your patience! 

It now only uses as many layers as it can actually store safely (which is up to 24).

**Closed by jonahfriedman** 2019-02-24 17:41 UTC
Labels: Nuke, bug

**Comment by kamensirashki** [comment] 2019-08-15 09:24
Hi Jonah,

I have precisely the same issue. We are using Criptomattes in Nuke. They have been rendered in Cinema4D with Redshift. I had updated to version 1.2.4 but the issue sill here. There isn't any issue when we rendering lolcaly, the problem is only when we send the renders to our farm through Deadline:
Error: >>> [15:32.33] ERROR: BUILDINGS1.Expression_key.expr0: Nothing named 'CryptoUserObjectID08.red' in '((CryptoUserObjectID00.red == 1.48445544448e+11) ? CryptoUserObjectID00.green : 0.0) + ((CryptoUserObjectID00.blue == 1.48445544448e+11) ? CryptoUserObjectID00.alpha : 0.0) + ((CryptoUserObjectID01.red == 1.48445544448e+11) ? CryptoUserObjectID01.green : 0.0) + ((CryptoUserObjectID01.blue == 1.48445544448e+11) ? CryptoUserObjectID01.alpha : 0.0) + ((CryptoUserObjectID02.red == 1.48445544448e+11) ? CryptoUserObjectID02.green : 0.0) + ((CryptoUserObjectID02.blue ==X_

Any ideas what could be the problem?

Many thanks.

**Comment by Andy-Gilbert** [comment] 2020-02-07 21:41
Hey Jonah :)

We are also having the exact same issue as Kamensirashki above. Local scene is fine. Deadline scene randomly gives us that error. We're on 1.2.4 also. The fact it doesn't happen to all our scenes and also some scenes will render ok in some instances is puzzling us. 

Any input is appreciated, we are also looking into deadline on our end.

Cheers!
Andy

**Comment by jonahfriedman** [comment] 2020-02-15 15:25
Hi Andy and @kamensirashki,

Is it possible that this was a comp created in an older version? If so, I'd suggest using "force update all" to ensure the channels are properly pre-registered.

The Cryptomatte gizmo has some invisible channel knobs that are updated with the required channels, and if that doesn't happen or there aren't enough, it causes problems. If you upgrade there are new channel knobs and the update functions populate them correctly (or should, at least), but that won't happen unless triggered somehow.  

In @kamensirashki's error message, it says that nothing is named 'CryptoUserObjectID08', because previously there were only knobs 0-7. Now there are 12 (0-11), and the keying expression does not use more channels than it can safely. 

Please let me know if "force update all" fixes it, otherwise I'll reopen this and we should try to get a reproduction.

**Comment by Andy-Gilbert** [comment] 2020-02-15 20:48
Hey thanks Jonah, we’ll try the “force update all” and get back to you.
