### ISSUE TITLE
Cryptomatte issue in Fusion 9

### ISSUE THREAD

**Issue by arka-nantes** [Psyop/Cryptomatte#46] opened 2017-11-24 08:55 UTC
In Fusion 9 when working on an animation (Multichannel EXR rendered with V-ray) , Cryptomatte loses the selected objects randomly.
It also seems to mix the Z-depth pass at some frames.
A temporary solution is to make a "cache to disk" for every Cryptomatte node in the composition but that's a huge waste of time.
We did 2 screenshots: the first one shows the issue and the other one is what it should be.
The second screenshot was taken after moving the matte locator which "updated" the Cryptomatte node getting him back to normal.
![crypto bug](https://user-images.githubusercontent.com/33952759/33208352-778e1410-d111-11e7-8e8b-635c7f9fa1a0.jpg)
![crypto good](https://user-images.githubusercontent.com/33952759/33208353-77b7deee-d111-11e7-80d1-bc54ad19bd5d.jpg)

**Comment by arka-nantes** [comment] 2017-11-28 15:57
It seems that we have found a temporary solution to the problem. In fact when rendering the sequence, Fusion keeps all rendered frames in memory. So the RAM is filling up till it have no space available. Cryptomatte starts to mess up when the RAM usage is approaching 100%.
The solution we have found is to write this little script command in the Frame Saved Script : fu:PurgeCache()
This line purges the cache after each frame saved, preventing the RAM to overload.

**Comment by cedricduriau** [comment] 2017-12-04 09:28
Hi @arka-nantes 

We tested the purge cache workaround you are mentioning and it indeed seems to work. My fear is still present that the "leak" is not just restricted to the lua memory buffer. But we need to dig into that.
In the meantime I will do some R&D code-wise on why purging lua memory seems to be a possible fix.

Cheers
Cedric

**Comment by AndrewFromSpaceDeluxe** [comment] 2017-12-04 21:30
I also have this issue, Cryptomatte loses the selected objects randomly.
Tried with the fu:PurgeCache() in the saver, but that didn't fix my problem. I have 3 cryptomattes in my comp.
Also tried with disk cache on and off, still not working for me.

Can i help somehow? Can i send you a few frames from my animation, so you can test?
(Fusion 9 with latest Cryptomatte)

**Comment by Gil-1** [comment] 2017-12-07 10:19
The PurgeCache solution works most of the time but it doesn't fully avoid the bug. I have less bugs with it but I still need to remake 3 frames out of a sequence of 350 frames.

**Comment by ricohofmann** [comment] 2018-01-08 08:09
I have the same problem. In my case it the cryptomatte was rendered well if i set the cryptomatte node to an viewer during the rendering. But tis is not really an workaround.

**Comment by cedricduriau** [comment] 2018-01-24 17:38
Hi all

Thanks for checking in. We have been aware of this issue for some time now, I've been in contact with some developers of Blackmagic but we/they have not come to a full fix yet.

I will keep you posted on further development.

Cheers
Cedric

**Comment by junglejuz** [comment] 2018-07-04 05:36
Are there any new developments on this issue yet?
This bug makes your Cryptomatte script almost useless, and at the very least incredibly frustrating.

**Comment by cedricduriau** [comment] 2018-07-04 06:44
Hi @junglejuz 

No, sadly I'm alone on this one.

What are your specs (Fusion version, OS+version, render engine)?
If you would be using V-Ray, could you provide me a test multi channel EXR?

Cheers
Cedric

**Comment by junglejuz** [comment] 2018-07-04 08:05
Fusion 9.0.2
Windows 10
Vray 3.6

not running out of RAM (I have 96Gb)

attached is a test frame
[VTi_LUNAR_SILVER.0020.zip](https://github.com/Psyop/Cryptomatte/files/2162094/VTi_LUNAR_SILVER.0020.zip)

**Comment by Gil-1** [comment] 2018-07-04 08:08
You need a sequence to view the bug. If you can maybe upload something like 50 frames.
I never had the issue with one frame.

**Comment by junglejuz** [comment] 2018-07-04 08:10
try this:
https://drive.google.com/file/d/1OjKr05lR8XX2SVE8601Qkt45L-Zya8tf/view?usp=sharing

**Comment by cedricduriau** [comment] 2018-07-04 08:10
Thanks!

**Comment by junglejuz** [comment] 2018-07-04 08:16
it's very unpredictable. Sometimes it works, Often it doesnt

**Comment by junglejuz** [comment] 2018-07-05 09:02
Hi Cedric. Did you manage to look at my files?
I'm trying to comp this project and it's causing me so much pain.

**Comment by cedricduriau** [comment] 2018-07-05 10:09
Hi @junglejuz 

I did, but I'm encountering some issues with the image stream of the google drive.
The single frame does fine. It seems like the manifest of the stream contains invalid characters.

In the download below you will find the input frames, the manifests for both single frame and stream frame, and a test comp to showcase the issue.

https://drive.google.com/file/d/1Jdb2iESbGF3ONy7DUgDE047jcU_V5z4K/view?usp=sharing

Cheers
Cedric

**Comment by junglejuz** [comment] 2018-07-05 10:49
I don't understand any of that, but i tried to load your comp and it gives me the following error

![image](https://user-images.githubusercontent.com/40817462/42319286-d2f0f204-8094-11e8-8850-83e8bd2c0b09.png)

**Comment by cedricduriau** [comment] 2018-07-05 15:25
Hi @junglejuz 

That's my mistake, sorry about that. Fixed the comp, try again with the files below.

What I mean is that the manifest inside the metadata of the EXR coming from the first zip you shared is perfectly fine, but when you check the manifest of the EXR frames from the image stream you shared, there the manifest contains invalid characters. Fusion cannot decode the manifest out of the metadata for those frames for Cryptomatte to process.

Are there any language specific (Roman, Japanese, Mandarin, ...) characters inside the object names in your 3D scene? I already encountered Cyrillic characters before and that worked fine.

If you want to understand more about what the manifest really is and how it is being used, I would recommend you to read the [specification document](  ../blob/1.2.0/specification/cryptomatte_specification.pdf  ) present in the repository.

Cheers
Cedric

https://drive.google.com/file/d/1jJ-G41WBNdHl7BuofHuOd8cSWmQw4jft/view?usp=sharing

PS: @jonahfriedman @acjones @vkoylazov: did you guys encounter encoding issues so far? (besides the Unicode/UTF-8  thread (#16) we had on here)

**Comment by junglejuz** [comment] 2018-07-05 15:50
Actually yes. The CAD model came from Japan and has thousands of objects, many of them named the same thing. Some of them I noticed at the bottom of the list have strange characters.

![image](https://user-images.githubusercontent.com/40817462/42333791-00c299d8-80bf-11e8-9899-dd2a07254747.png)

**Comment by jonahfriedman** [comment] 2018-07-05 16:00
@cedricdu  I have never seen encoding issues after we standardized on UTF-8. 

@junglejuz - Many objects named the same thing are no problem from the standard's perspective, they will just be the same matte. Those two at the bottom though don't look like they're working correctly, and may be invalid in some way, so I wouldn't be at all suprised something like that led to the invalid characters in the manifest.

**Comment by cedricduriau** [comment] 2018-07-05 21:01
@jonahfriedman Ok, thanks for confirming Jonah!
@junglejuz Well I'd suggest checking the render setup and re-rendering those frames.

**Comment by cedricduriau** [comment] 2018-07-05 21:11
As an update to this general issue, today at Grid we were able to reproduce this issue by making a comp with 10+ Cryptomatte fuses that cause every frame to fill the memory to 95%. The output of this comp was full of glitches, as shown in the first post.

I will prepare a standalone setup and send this to Blackmagic, hoping once more to get an answer on this topic. If I haven't said it enough, my apologies for this issue, it really does concern us all.

As always, I'll keep you posted if I get any news.

Cheers
Cedric

**Comment by bintangsenja** [comment] 2018-08-08 06:05
Hi @cedricdu , Thank you for everything you guys done Cryptomatte for Fusion. 

We are considering to implement fusion cryptomatte in our next animation show projects. Right now we just testing it, but anyway, I go through all the fusion issues thread, but still can't find anything regarding the crypto layer selection in fusion. 

Is this related to issue about multi crypto layer in one exr file ? do you think it best for us to just use a single cryptomatte for each exr layer in fusion ? 
Please advice, Thanks :)

**Comment by cedricduriau** [comment] 2018-08-08 07:13
Hi @bintangsenja 

First of all, thanks!

Second, that's a great idea, we've done two feature films using Cryptomatte in Fusion and that was a great improvement to the comp workflow, if I may say so myself.

Third, would you mind creating a new issue thread for this topic, and in that topic provide an example frame and an in Fusion screenshot of what you mean?

Cheers
Cedric

**Comment by dantrodgers** [comment] 2018-12-04 00:36
Having the same issue (slipped masks), also when I try to cache the cryptomatte I just get a force quit from Fusion.

**Comment by pedromartm** [comment] 2019-12-09 12:35
Hi @cedricduriau, same as @bintangsenja we are testing Cryptomatte in Fusion to implement it in production of a feature film. Sadly we encounter the same problem, and even the purge cache workaround don't work. 
Any news on this bug, or some workaround?

Thanks for all the effort put in this amazing tool !!!

**Comment by cedricduriau** [comment] 2019-12-09 12:46
Hi @pedromartm 

Thanks for the kind words.
There are no updates on this bug so far. I have passed the ball to Blackmagic Design a long time ago. They never really reported back or cared to elaborate.

Cache purging will indeed not consistently fix the issue. The only route I thought might help was to have Cryptomatte as a Fusion plugin.

Some individuals took it upon themselves to do this exact thing. Sadly, along with the fact that it is not free, the problems seem to still be there, which increase my concerns towards the Fusion back end.

As long as Blackmagic Design will not address this, there is little we can do.

I am thoroughly sorry for the state of the matter and I wish you best of luck with the feature.

Cheers
Cédric

**Comment by cedricduriau** [comment] 2021-04-13 19:49
Fixed with cedricduriau#11

**Comment by pedromartm** [comment] 2021-04-13 19:58
Thanks a lot, we'll try it!!!

**Comment by cedricduriau** [comment] 2021-04-13 20:00
Pleasure, beta versions were released on my fork. Official release coming soon.

**Closed** 2021-04-24 16:59 UTC
Labels: Fusion, bug
