### ISSUE TITLE
Error when baking Cryptomatte gizmo to group

### ISSUE THREAD

**Issue by simonbjork** [Psyop/Cryptomatte#58] opened 2018-01-12 07:34 UTC
If the Cryptomatte gizmo has been baked into a group it throws an error when reopening the script (or just simply copy/paste the group in the DAG).

If you run .Class() on the knob you see that it's now an Obsolete_Knob and you get the following error:

`Obsolete_knob ColorKey call is wrong, probably a missing NULL for script argument.`

Maybe the gizmo should use a basic Color_Knob instead? I'm not sure If the Eyedropper_Knob is used much.

**Comment by acjones** [comment] 2018-01-12 08:24
Versions of Cryptomatte prior to 1.2.0 did actually use a Color_Knob.  The big difference is that the eyedropper knob's return value includes not only the pixel color, but also the pixel position.  This enables us to always fetch the color of the correct image buffer in the gizmo using the "sample" function, regardless of what the user is viewing when they select a color.  That behavior makes it possible to support keyable surfaces that don't include the Cryptomatte ID values, such as "edges" and "none," and to pick keys on the image itself.  Most importantly, though, it fixed the issue we had with some GPUs returning inaccurate values from the viewer when picking.  

I would suggest (and greatly appreciate!) logging this as a bug with the Foundry.  We also saw the same errors when we would edit the gizmo, so I can vouch that this is a Nuke bug.  The knob type, which should be 36, gets lost and reverts to 0 when the script is saved.  It would be great to see this fixed, as Eyedropper_Knobs are surprisingly useful for all the above reasons, despite being relatively rare, as you said.

I'm going to close this, since switching back to a Color_Knob would cause more significant regressions than what you're experiencing.  The 1.1.4 tag is still there, and functional, should you need it before we're able to get a bugfix from The Foundry.  (But I'd definitely recommend sticking with 1.2.0, and just living with this issue if you can).

Also, check out issue #45 .  If you're trying to convert to Groups to make sure scripts don't break outside of your pipeline, of after gizmo updates, there's some potentially useful information about that.

**Closed by acjones** 2018-01-12 08:24 UTC

**Comment by simonbjork** [comment] 2018-01-12 09:10
Ah, thanks, didn't know it saved the pixel position as well. Cool. 

I haven't actually had any issues with it yet myself, but I could imagine this being problematic as we sometimes need to bake gizmos before sending scripts to 3:rd party etc. Also, it would break scripts that might have been baked before archiving.

I guess a workaround would be to implement a custom color picker knob using PySide and the PyCustom_Knob. But that is a can of worms so I'm not sure I'd recommend that. Or maybe connect a callback to a Color_Knob that also returns the mouse position (and stores it somewhere).

I'll try to get it logged with TF but I would't expect it to be fixed in a while.

**Comment by dgirondi** [comment] 2018-01-12 10:22
When it comes to sending to third party and archival I think it's best to decryptomatte everything. Having the Cryptomatte gizmos replaced by Expression nodes ensures things will work no matter where.

As for the Nuke bug, I believe it's a known one and a really old one for what is worth. I remember discussing this with TF circa Nuke 6 beta. Any knob that isn't exactly exposed to the user from the GUI tend to not be correctly saved or copied.
